name: Build and Push Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Manual tag name'
        default: 'latest'
        type: string

jobs:
  push_to_registries:
    name: Build and Push
    runs-on: ubuntu-20.04
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install Docker CLI
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Docker Network Discovery
        run: |
          echo "Checking DOCKER_HOST: $DOCKER_HOST"
          
          echo "--- Testing: localhost ---"
          DOCKER_HOST=tcp://localhost:2375 docker ps && echo "SUCCESS: localhost is the winner" || echo "FAIL: localhost unreachable"
          
          echo "--- Testing: docker-in-docker sidecar ---"
          DOCKER_HOST=tcp://docker-in-docker:2375 docker ps && echo "SUCCESS: sidecar name is the winner" || echo "FAIL: sidecar name unreachable"
          
          echo "--- Final Environment ---"
          docker version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Log in to Codeberg Container Registry
        uses: docker/login-action@v3
        with:
          registry: codeberg.org
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_PAT }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            codeberg.org/${{ github.repository }}
            kylemmkay/deezer-engine
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest
            type=raw,value=${{ github.event.inputs.tag_name }},enabled=${{ github.event_name == 'workflow_dispatch' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}